//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholesaleStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyShipment
    {
        public int Id { get; set; }
        public int SupplyContentId { get; set; }
        public int ProductInStorageId { get; set; }
        public System.DateTime Date { get; set; }
        public int Count { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ProductsInStorage ProductsInStorage { get; set; }
        public virtual SupplyContent SupplyContent { get; set; }
    }
}
